apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: rodoben007/logger-service:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
            - containerPort: 5001
            - containerPort: 50001

---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - port: 80
      protocol: TCP
      name: web-port
      targetPort: 80

    - port: 5001
      protocol: TCP
      name: rpc-port
      targetPort: 5001

    - port: 50001
      protocol: TCP
      name: grpc-port
      targetPort: 50001
